name: "${PROJECT_NAME}"
services:
  redis:
    container_name: "${REDIS_CONTAINER_NAME}"
    image: "redis/redis-stack:${REDIS_VERSION}"
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - "REDIS_ARGS=${REDIS_ARGS}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "com.docker.compose.publishers=redis,6379,${REDIS_PORT}"
